const cities = [
'Santander',
'Torrelavega',
'Castro Urdiales',
'Camargo',
'Piélagos',
'El Astillero',
'Laredo',
'Santoña',
'Los Corrales de Buelna	',
'Reinosa',
'Santa Cruz de Bezana',
'Cabezón de la Sal',
'Reocín',
'Colindres',
'Suances',
'Santa María de Cayón',
'Medio Cudeyo',
'Marina de Cudeyo',
'San Vicente de la Barquera	',
'Ribamontán al Mar',
'Santillana del Mar',
'Cartes',
'Campoo de Enmedio',
'Polanco',
'Miengo',
'Ampuero',
'Villaescusa',
'Bárcena de Cicero',
'Entrambasaguas',
'Val de San Vicente',
'Alfoz de Lloredo',
'Puente Viesgo',
'Comillas',
'Valdáliga',
'Liérganes',
'Noja',
'Ramales de la Victoria',
'Voto',
'San Felices de Buelna',
'Corvera de Toranzo	',
'Ribamontán al Monte',
'Mazcuerras',
'Selaya',
'Hermandad de Campoo de Suso',
'Guriezo',
'Arnuero',
'Arenas de Iguña',
'Bareyo',
'Molledo',
'Castañeda',
'Villacarriedo',
'Penagos',
'Potes',
'Riotuerto',
'Limpias',
'Soba',
'Meruelo',
'Santiurde de Toranzo',
'Argoños',
'Valdeolea',
'Hazas de Cesto',
'Rionansa',
'Cillorigo de Liébana',
'Valderredible',
'Ruesga',
'Villafufre',
'Cabuérniga',
'Camaleño',
'Solórzano',
'Ruente',
'Liendo',
'Rasines',
'Vega de Pas',
'Vega de Liébana',
'Luena',
'Udías',
'Bárcena de Pie de Concha',
'Escalante',
'Ruiloba',
'Campoo de Yuso',
'Herrerías',
'Cabezón de Liébana',
'Cieza',
'San Pedro del Romeral',
'Arredondo',
'Saro',
'Miera',
'San Roque de Riomiera',
'Los Tojos',
'Valle de Villaverde',
'Anievas',
'Peñarrubia',
'Pesaguero',
'Santiurde de Reinosa',
'Lamasón',
'Valdeprado del Río',
'Las Rozas de Valdearroyo',
'Polaciones',
'Tudanca',
'San Miguel de Aguayo',
'Pesquera',
'Tresviso'
];

const works = [ 'Mudanzas', 'Vaciados de pisos', 'Reformas', 'Pintura', 'Recogida muebles', 'Limpiezas' ];

export default{ cities, works }